name: Deploy Web

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - 'packages/ui/**'
      - 'packages/eslint-config/**'
      - 'packages/jest-config/**'
      - 'packages/typescript-config/**'
      - 'pnpm-lock.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Vercel CLI
        run: pnpm add -g vercel

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy Project
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
