name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'packages/api/**'
      - 'packages/eslint-config/**'
      - 'packages/jest-config/**'
      - 'packages/typescript-config/**'
      - 'pnpm-lock.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build affected packages
        run: pnpm turbo run build --filter=@repo/api...

      - name: Generate Prisma client
        run: pnpm prisma generate --schema apps/api/prisma/schema.prisma

      - name: Deploy to Render
        if: success()
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
